name: My First Workflow

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello, GitHub Actions!"

      - name: Print Date
        run: date

      - name: Print Goodbye
        run:|
          echo "Workflow completed!"
          echo "thank you"
